### ISSUE TITLE
More than one document returned in composer.

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/public-contracts#27]
Traceback (most recent call last):
```
  File "/home/littlepig/webapps/publics/public-contracts/law/models.py", line 123, in compose_text
    return compose_text(self)

  File "/home/littlepig/webapps/publics/public-contracts/law/composer.py", line 191, in compose_text
    text = add_references(text)

  File "/home/littlepig/webapps/publics/public-contracts/law/composer.py", line 114, in add_references
    return re.sub(create_regex(), replace_docs, text)

  File "/usr/local/lib/python3.3/re.py", line 170, in sub
    return _compile(pattern, flags).sub(repl, string, count)

  File "/home/littlepig/webapps/publics/public-contracts/law/composer.py", line 104, in replace_docs
    doc = Document.objects.get(type_id=matched_type.id, number=matched_number)

  File "/home/littlepig/webapps/publics/lib/python3.3/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)

  File "/home/littlepig/webapps/publics/lib/python3.3/django/db/models/query.py", line 310, in get
    (self.model._meta.object_name, num))

law.models.MultipleObjectsReturned: get() returned more than one Document -- it returned 2!```

**Comment by jorgecarleitao** [comment]
Fixed in c5ce07f702bca74577c7d61b52edc8d9a6e37746.
