### ISSUE TITLE
Compose text failed in dre_doc_id=67040491

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/public-contracts#62]
I'm getting the following error on production:
```
ERROR 2015-04-22 17:02:43,326 models Compose text failed in dre_doc_id=67040491
Traceback (most recent call last):
  File ".../law/models.py", line 81, in compose_text
    return composer.compose_text(self)
  File ".../law/composer.py", line 329, in compose_text
    text = organize_text(document.text)
  File ".../law/composer.py", line 348, in organize_text
    soup = organize_soup(soup)
  File ".../law/composer.py", line 451, in organize_soup
    search = re.search(hierarchy_regex[format], element.text)
  File ".../lib/python3.3/site-packages/bs4/element.py", line 675, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'ProcessingInstruction' object has no attribute 'text'
```

Other documents: `67011879`, `67011878`, `67040491`, `66997033`.

**Comment by jorgecarleitao** [comment]
Fixed in e08253e96fd3cc2f8294009d1b074bc878861abf.
